### ISSUE TITLE
Add Z3 binaries to Maven

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#88]
Currently automatic installation of Z3 binaries works only with Ivy with the SoSy-Lab repository. The binaries are not published to Maven Central (missing from https://repo1.maven.org/maven2/org/sosy-lab/javasmt-solver-z3/z3-4.4.1-1558-gf96cfea/). As Maven is more common than Ivy, making Z3 available automatically via Maven would be nice for users.

**Comment by cheshire** [comment]
I'll figure out the binaries, but I'm not sure whether it would be possible to tell JavaSMT how to automatically pick them up, as Maven does not dump all JARs in one folder..

**Comment by breandan** [comment]
Maybe it is possible to implement something similar to what [Z3-TurnKey](https://github.com/tudo-aqua/z3-turnkey) has done, either by directly adding it as a dependency or building a custom multiplatform artifact and [dispatching to the correct binary at runtime](https://github.com/tudo-aqua/z3-turnkey/blob/master/src/main/java/com/microsoft/z3/Z3Loader.java)? It would be great if JavaSMT were able to publish a fully-self-contained Maven artifact for all supported platforms, as I do not think Ivy is very widely used anymore.

**Comment by kfriedberger** [comment]
Thanks for the reference.
Most of it (i.e., OS-based searching for the library) already looks like our own approach. I will take a look at the unpacking part.

We know that Maven it widely known and used in many projects.
The Ant/Ivy approach seems to be more flexible and suits well with our own build-infrastructure.

**Comment by breandan** [comment]
FWIW, I was able to get this to work on Ubuntu 18.04 by first copying the `libz3.so` and `libz3java.so` files from Z3 into `/usr/lib` as described in the [Getting Started](https://github.com/sosy-lab/java-smt/blob/master/doc/Getting-started.md#binaries-for-native-solvers-mathsat-and-z3) page. After initially receiving the error pasted below, I was able to resolve it by adding a dependency to the [`io.github.tudo-aqua:z3-turnkey:4.8.7.1`](https://search.maven.org/artifact/io.github.tudo-aqua/z3-turnkey/4.8.7.1/jar) artifact on Maven Central, and then I was able to JavaSMT with Z3 as expected.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: org.sosy_lab.common.configuration.InvalidConfigurationException: The SMT solver Z3 is not available on this machine because of missing libraries (com/microsoft/z3/Native). You may experiment with SMTInterpol by setting solver.solver=SMTInterpol.
	at org.sosy_lab.java_smt.SolverContextFactory.generateContext(SolverContextFactory.java:173)
	at org.sosy_lab.java_smt.SolverContextFactory.createSolverContext(SolverContextFactory.java:285)
	at edu.mcgill.kaliningraph.smt.TestSMTKt.<clinit>(TestSMT.kt:10)
Caused by: java.lang.NoClassDefFoundError: com/microsoft/z3/Native
	at org.sosy_lab.java_smt.solvers.z3.Z3SolverContext.create(Z3SolverContext.java:140)
	at org.sosy_lab.java_smt.solvers.z3.Z3LoadingFactory.generateSolverContext(Z3LoadingFactory.java:41)
	at org.sosy_lab.java_smt.SolverContextFactory.generateContext0(SolverContextFactory.java:224)
	at org.sosy_lab.java_smt.SolverContextFactory.generateContext(SolverContextFactory.java:170)
	... 2 more
Caused by: java.lang.ClassNotFoundException: com.microsoft.z3.Native
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at org.sosy_lab.common.ExtendedURLClassLoader.loadClass(ExtendedURLClassLoader.java:79)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 6 more
```

**Comment by kfriedberger** [comment]
With #211 solved, we have several solvers (including MathSAT5 and Z3) in Maven.
