### ISSUE TITLE
Yices2 not working on 4.0.0

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#311]
I am getting the following error when trying to run yices2 with the new release 4.0.0.
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.sosy_lab.java_smt.basicimpl.AbstractFormulaManager.<init>(org.sosy_lab.java_smt.basicimpl.FormulaCreator, org.sosy_lab.java_smt.basicimpl.AbstractUFManager, org.sosy_lab.java_smt.basicimpl.AbstractBooleanFormulaManager, org.sosy_lab.java_smt.api.IntegerFormulaManager, org.sosy_lab.java_smt.api.RationalFormulaManager, org.sosy_lab.java_smt.basicimpl.AbstractBitvectorFormulaManager, org.sosy_lab.java_smt.basicimpl.AbstractFloatingPointFormulaManager, org.sosy_lab.java_smt.basicimpl.AbstractQuantifiedFormulaManager, org.sosy_lab.java_smt.basicimpl.AbstractArrayFormulaManager, org.sosy_lab.java_smt.basicimpl.AbstractSLFormulaManager, org.sosy_lab.java_smt.basicimpl.AbstractStringFormulaManager)'
        at org.sosy_lab.java_smt.solvers.yices2.Yices2FormulaManager.<init>(Yices2FormulaManager.java:51)
        at org.sosy_lab.java_smt.solvers.yices2.Yices2SolverContext.create(Yices2SolverContext.java:75)
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext0(SolverContextFactory.java:280)
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext(SolverContextFactory.java:205)
        at org.sosy_lab.java_smt.SolverContextFactory.createSolverContext(SolverContextFactory.java:311)
```
From the trace, it seems there might be a mismatch in the number of parameters, but I don't understand why because from [here](https://github.com/sosy-lab/java-smt/blob/6194eba621a43e25ac9758e803b11ccfd307a589/src/org/sosy_lab/java_smt/solvers/yices2/Yices2FormulaManager.java#L52-L65) it seems all parameters are correctly passed to the super constructor in [here](https://github.com/sosy-lab/java-smt/blob/6194eba621a43e25ac9758e803b11ccfd307a589/src/org/sosy_lab/java_smt/basicimpl/AbstractFormulaManager.java#L131-L147).

Most other solvers (the ones we usually use) work fine, so I assume the problem is in the Yices2 implementation of the api.

**Comment by kfriedberger** [comment]
Thanks for reporting. It is always good to have such eager users.
Our publication steps for GPL-licensed components like Yices2 are a bit rusty.
 
The artifact `javasmt-yices2` was released in version 4.0.1. Give Maven a few minutes for a sync.

We will provide a new release of the main library of JavaSMT later, where we fix some minor issues related to the release 4.0.0, such as documentation and versioning.

**Comment by hernanponcedeleon** [comment]
Release 4.0.2 worked like a charm
