### ISSUE TITLE
NoSuchMethodError exception in opensmt

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#665]
I encountered another exception when trying to update to the latest solvers (using `opensmt` version `2.9.2-ge4c80308`)
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.sosy_lab.java_smt.solvers.opensmt.api.MainSolver.stop()'
        at org.sosy_lab.java_smt.solvers.opensmt.OpenSmtAbstractProver.isUnsatImpl(OpenSmtAbstractProver.java:214)
        at org.sosy_lab.java_smt.basicimpl.AbstractProver.isUnsat(AbstractProver.java:173)
        at org.sosy_lab.java_smt.basicimpl.withAssumptionsWrapper.BasicProverWithAssumptionsWrapper.isUnsat(BasicProverWithAssumptionsWrapper.java:65)
```

**Comment by daniel-raffler** [comment]
Hello Hernan,
is that with the JavaSMT [6.0.0](https://mvnrepository.com/artifact/org.sosy-lab/java-smt/6.0.0) release? OpenSMT renamed a method recently, so the last version that will work with JavaSMT 6.0.0 is `2.9.0-gef441e1c`. If you want to upgrade to `2.9.2-ge4c80308`, JavaSMT [6.0.0-148-gba08f432a](https://mvnrepository.com/artifact/org.sosy-lab/java-smt/6.0.0-148-gba08f432a) should work

**Comment by hernanponcedeleon** [comment]
Yes, that was with `6.0.0`. The problem is solved with `6.0.0-148-gba08f432a`. 

Sorry for all the issues. There were too many changes with the recent update and the usual solution of just updating the versions seems not to work anymore (still my fault for assuming that blindly updating the version numbers was enough).

Right now, I am only experiencing problems with yices2, but @baierd already told me there is a known issue.
